include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    avoid_web_libraries_in_flutter: false