name: flutterconflatam
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  universal_html: 2.2.3
  js: 0.6.7
  cupertino_icons: 1.0.6
  material_symbols_icons: ^4.2668.0
  web_socket_channel: 2.4.0
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/sup_frontal/
    - assets/img/sup_lingual/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100